# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c2121b0170ca5e23250c6ceb25f2b9f3a45850deaebaf0fb47188d91cbd9232c80e25c911737d0851bbb361b36dd17ad8bd2eaa246e01461ce56de73d0bd3d5

test:
  secret_key_base: 1e9268da906336be1d4d4d9c96bddc17417d39a8d36d3fcf385b87d3ff4078f5eba368dd0310a74ddbea41ef90562f9d94d9223341252618ffbcd586ba347774

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
